#pragma once

#define __attr_alias(symbol)            __attribute__((alias(#symbol)))
#define __attr_always_inline            inline __attribute__((__always_inline__))
#define __attr_always_unused            __attribute__((__unused__))
#define __attr_always_used              __used __maybe_unused
#define __attr_api                      __attribute__((visibility("default")))
#define __attr_cleanup(func)            __attribute__((__cleanup__(func)))
#define __attr_cold                     __attribute__((__cold__))
#define __attr_compiletime_warning(msg) __attribute__((__warning__(msg)))
#define __attr_constructor              __attribute__((constructor))
#define __attr_counted_by(type)         __attribute__((counted_by(type)))
#define __attr_counted_by_or_null(type) __attribute__((counted_by_or_null(type)))
#define __attr_deprecated(msg)          __attribute__((deprecated(msg)))
#define __attr_destructor               __attribute__((destructor))
#define __attr_flag_enum                __attribute__((__flag_enum__))
#define __attr_fmt_printf(fmt, varargs) __attribute__((format(printf, fmt, varargs)))
#define __attr_fmt_scanf(fmt, varargs)  __attribute__((format(scanf, fmt, varargs)))
#define __attr_hot                      __attribute__((__hot__))
#define __attr_malloc                   __attribute__((__malloc__))
#define __attr_matrix(rows, cols)       __attribute__((matrix_type(rows, cols)))
#define __attr_maybe_unused             __attribute__((__unused__))
#define __attr_nodiscard                __attribute__((__warn_unused_result__))
#define __attr_noinline                 __attribute__((__noinline__))
#define __attr_noreturn                 __attribute__((__noreturn__))
#define __attr_overloaded               __attribute__((__overloadable__))
#define __attr_pure                     __attribute__((__pure__))
#define __attr_sized_by(type)           __attribute__((sized_by(type)))
#define __attr_sized_by_or_null(type)   __attribute__((sized_by_or_null(type)))
#define __attr_used                     __attribute__((__used__))
#define __attr_vector(size)             __attribute__((ext_vector_type(size)))

#define likely(expr)   __builtin_expect(!!(expr), 1)
#define unlikely(expr) __builtin_expect(!!(expr), 0)
